=== odow/SDDP.jl/src/plugins/cuts.schema.json
{
    "$schema": "https://json-schema.org/schema#",
    "$id": "https://github.com/odow/SDDP.jl/tree/master/src/plugins/cuts.schema.json",
    "title": "The schema for SDDP.jl cuts",
    "type": "array",
    "items": {
        "type": "object",
        "required": ["node"],
        "properties": {
            "node": {
                "type": "string"
            },
            "single_cuts": {
                "type": "array",
                "items": {
                    "$ref": "#/definitions/Cut"
                }
            },
            "multi_cuts": {
                "type": "array",
                "items": {
                    "$ref": "#/definitions/Cut",
                    "required": ["realization"],
                    "properties": {
                        "realization": {
                            "type": "integer"
                        }
                    }
                }
            },
            "risk_set_cuts": {
                "type": "array",
                "items": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                }
            }
        }
    },
    "definitions": {
        "Cut": {
            "type": "object",
            "required": ["intercept", "coefficients"],
            "properties": {
                "intercept": {
                    "type": "number"
                },
                "coefficients": {
                    "type": "object"
                }
            }
        }
    }
}

=== odow/SDDP.jl/v1.10.4/tutorial/convex.cuts.json
[{"risk_set_cuts":[],"node":"1","single_cuts":[{"state":{"x":0.0},"intercept":243326.5932873207,"coefficients":{"x":-317616.6666712048}},{"state":{"x":0.0},"intercept":321380.875475521,"coefficients":{"x":-318249.99997748446}},{"state":{"x":0.0},"intercept":346483.98068044573,"coefficients":{"x":-318250.0000028512}},{"state":{"x":0.0},"intercept":354558.1883998782,"coefficients":{"x":-318250.0000165849}},{"state":{"x":0.0},"intercept":357155.19103196025,"coefficients":{"x":-318250.00002266077}},{"state":{"x":0.0},"intercept":357990.49560985994,"coefficients":{"x":-318250.0000249221}},{"state":{"x":0.0},"intercept":358259.16447035177,"coefficients":{"x":-318250.00002568774}},{"state":{"x":0.3349461006592544},"intercept":251748.9830689898,"coefficients":{"x":-318249.999969381}},{"state":{"x":0.0},"intercept":358373.37431914586,"coefficients":{"x":-318250.00002601923}},{"state":{"x":0.3349461006592544},"intercept":251785.71772930954,"coefficients":{"x":-318249.9999694142}},{"state":{"x":0.0},"intercept":358385.1897210881,"coefficients":{"x":-318250.00002605375}},{"state":{"x":0.3349461006592544},"intercept":251789.51805635216,"coefficients":{"x":-318249.99996941764}},{"state":{"x":0.0},"intercept":358386.4120650849,"coefficients":{"x":-318250.0000260573}},{"state":{"x":0.0},"intercept":358386.5077481086,"coefficients":{"x":-318250.0000260576}},{"state":{"x":2.6698924476020394},"intercept":19658.9789923926,"coefficients":{"x":-1583.3333403082606}},{"state":{"x":7.33494488161516},"intercept":31772.19902977808,"coefficients":{"x":-1504.166685140485}},{"state":{"x":10.334948405749303},"intercept":45834.52975895078,"coefficients":{"x":-1428.9583568997439}},{"state":{"x":9.00969038525014},"intercept":65113.07923635773,"coefficients":{"x":-1357.510447338956}},{"state":{"x":8.67474198765553},"intercept":81902.34421775503,"coefficients":{"x":-1289.6349340196143}},{"state":{"x":8.339793590091373},"intercept":97680.1946498979,"coefficients":{"x":-1225.1531971293794}},{"state":{"x":8.004845192505051},"intercept":112505.79882724976,"coefficients":{"x":-1163.895547926387}},{"state":{"x":10.669896794928016},"intercept":123117.83443972688,"coefficients":{"x":-1105.7007769259594}},{"state":{"x":10.334948397598945},"intercept":136368.943829842,"coefficients":{"x":-1050.4157447958562}},{"state":{"x":5.334948366371744},"intercept":153472.67383772606,"coefficients":{"x":-997.8968728870422}},{"state":{"x":0.964069829593098},"intercept":208179.8326162348,"coefficients":{"x":-102045.1673724623}},{"state":{"x":0.6291214702143574},"intercept":258347.80689535462,"coefficients":{"x":-318249.99988189765}},{"state":{"x":0.0},"intercept":495379.7631078264,"coefficients":{"x":-349614.3029621213}},{"state":{"x":0.6698966982736608},"intercept":288752.2881948821,"coefficients":{"x":-318249.99972594256}},{"state":{"x":5.334948362384089},"intercept":164866.86381845697,"coefficients":{"x":-1265.3346957972647}},{"state":{"x":0.2739182511509154},"intercept":424627.84004643344,"coefficients":{"x":-318250.0000038391}},{"state":{"x":0.9739181624306341},"intercept":264109.2771632086,"coefficients":{"x":-102362.4994456396}},{"state":{"x":1.6739180744011717},"intercept":212634.63651560375,"coefficients":{"x":-33765.480921892355}},{"state":{"x":1.3389696972424379},"intercept":231569.98087971067,"coefficients":{"x":-112104.90209370306}},{"state":{"x":1.338969696130989},"intercept":232074.49849789919,"coefficients":{"x":-46825.62227993777}},{"state":{"x":1.6739180744011721},"intercept":216390.3325834567,"coefficients":{"x":-46825.62096436702}},{"state":{"x":1.3389696972424376},"intercept":232074.49844605895,"coefficients":{"x":-46825.622280733805}},{"state":{"x":1.338969693590646},"intercept":232074.49861705632,"coefficients":{"x":-46825.62228073427}},{"state":{"x":0.9739181624306348},"intercept":272494.0475221761,"coefficients":{"x":-112104.90235970907}},{"state":{"x":1.6739180744011721},"intercept":216390.33260619617,"coefficients":{"x":-46825.62101959178}},{"state":{"x":1.3389696972424376},"intercept":232074.4984974808,"coefficients":{"x":-46825.62236521589}},{"state":{"x":1.338969706239835},"intercept":232074.49807615488,"coefficients":{"x":-46825.6223649678}},{"state":{"x":0.6389697860051539},"intercept":323331.859066264,"coefficients":{"x":-332444.77935708023}},{"state":{"x":1.3389696972847906},"intercept":236282.50970202603,"coefficients":{"x":-116599.91552189991}},{"state":{"x":0.6389698060053552},"intercept":330916.5590794864,"coefficients":{"x":-332444.7792868083}},{"state":{"x":1.3389697172849926},"intercept":238684.33114696768,"coefficients":{"x":-116599.91556221395}},{"state":{"x":2.669896764446652},"intercept":192428.68371135215,"coefficients":{"x":-12043.094698375427}},{"state":{"x":5.334948382513215},"intercept":179152.0982748006,"coefficients":{"x":-5164.335942853634}},{"state":{"x":8.998767290632536},"intercept":174889.8699015641,"coefficients":{"x":-2986.0623817984833}},{"state":{"x":8.898767492172237},"intercept":187808.68727526162,"coefficients":{"x":-2836.75928174278}},{"state":{"x":7.5987674311817095},"intercept":203249.27907753564,"coefficients":{"x":-2694.921335689987}},{"state":{"x":8.29876737221291},"intercept":212572.91399759002,"coefficients":{"x":-2560.17528024302}},{"state":{"x":8.998767313060899},"intercept":221473.0367570244,"coefficients":{"x":-2432.1665262900933}},{"state":{"x":10.334948382131143},"intercept":228498.75596066352,"coefficients":{"x":-2310.5582083505774}},{"state":{"x":10.0999999519246},"intercept":238733.8720275769,"coefficients":{"x":-2195.0303064995956}},{"state":{"x":10.799999967069388},"intercept":246441.57596928414,"coefficients":{"x":-2085.278798780882}},{"state":{"x":8.499999980271575},"intercept":259741.693943065,"coefficients":{"x":-1981.0148692666062}},{"state":{"x":9.199999995185614},"intercept":266431.3369417497,"coefficients":{"x":-1881.9641431925513}},{"state":{"x":11.899999990155353},"intercept":269057.22419768985,"coefficients":{"x":-1787.8659451234744}},{"state":{"x":14.599999991673801},"intercept":271584.73901807534,"coefficients":{"x":-1698.4726522085411}},{"state":{"x":12.299999986593837},"intercept":282084.8990222906,"coefficients":{"x":-1613.5490250397775}},{"state":{"x":0.0},"intercept":606804.7094756872,"coefficients":{"x":-318249.9999724368}},{"state":{"x":0.029699038933451712},"intercept":617581.4438156808,"coefficients":{"x":-318249.99999251467}},{"state":{"x":0.7296989501992199},"intercept":407664.30857179395,"coefficients":{"x":-102240.12442165897}},{"state":{"x":0.0},"intercept":649370.5412339632,"coefficients":{"x":-349676.03940428357}},{"state":{"x":0.029699001871377386},"intercept":646059.0151063582,"coefficients":{"x":-349676.03940101556}},{"state":{"x":0.7296989131371451},"intercept":417107.28166336287,"coefficients":{"x":-112314.0794377364}},{"state":{"x":0.02969900186335297},"intercept":649375.179388943,"coefficients":{"x":-352866.1251328376}},{"state":{"x":0.7296989131291214},"intercept":418157.40034669504,"coefficients":{"x":-113324.27323516461}},{"state":{"x":0.36464742214981744},"intercept":532295.3954019079,"coefficients":{"x":-353186.0197809969}},{"state":{"x":1.0646473334151714},"intercept":380545.3514768302,"coefficients":{"x":-113425.57292010638}},{"state":{"x":0.7296989131291217},"intercept":418538.4397446421,"coefficients":{"x":-113425.5732226361}},{"state":{"x":0.36464746275871684},"intercept":532775.4775190728,"coefficients":{"x":-353218.0981118779}},{"state":{"x":1.0646473740240705},"intercept":380698.7560958628,"coefficients":{"x":-113435.73105857345}},{"state":{"x":0.7296989537380182},"intercept":418694.60170755663,"coefficients":{"x":-113435.73136095713}},{"state":{"x":2.6698968431295627},"intercept":304177.3850211096,"coefficients":{"x":-2094.290616906698}},{"state":{"x":5.33494842171494},"intercept":304735.1946263002,"coefficients":{"x":-1989.5761106492348}},{"state":{"x":1.6700357027909358},"intercept":343019.32248112914,"coefficients":{"x":-37501.34740088245}},{"state":{"x":2.0049849644681013},"intercept":331774.5185455879,"coefficients":{"x":-13458.76019541362}},{"state":{"x":1.6700357040520852},"intercept":346400.64711907686,"coefficients":{"x":-40816.589025424284}},{"state":{"x":0.9700366399707983},"intercept":405331.636024354,"coefficients":{"x":-117064.33849263791}},{"state":{"x":1.670036551838279},"intercept":350802.2524316202,"coefficients":{"x":-41965.647959656715}},{"state":{"x":3.3397951826475487},"intercept":319461.0964894269,"coefficients":{"x":-5845.2740123051335}},{"state":{"x":3.0048468569530917},"intercept":323376.5469641294,"coefficients":{"x":-4652.007034299091}},{"state":{"x":2.6698975965691405},"intercept":330684.41784726793,"coefficients":{"x":-16235.392969557945}},{"state":{"x":5.334948336177132},"intercept":316447.721931377,"coefficients":{"x":-3896.2711289203303}}],"multi_cuts":[]}]
